---
- name: Install python3, docker and docker compose
  hosts: aws
  become: yes # by default switch to root user
  # gather_facts: False
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python # do this task with python 2
      yum: # yum does not support python3
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x # the mode of the downloaded file
    - name: Start docker daemon
      systemd:
        name: docker
        state: started
    - name: Install docker and docker-compose python modules
      pip:
        name: 
          - docker
          - docker-compose
    
- name: Add ec2-user to docker group
  hosts: aws
  become: yes
  tasks:
    - name: Add ec2-user to docker group
      user: 
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server session # user must log out and in again so that previous step is activated
      meta: reset_connection
      
# - name: Test docker pull
#   hosts: aws
#   tasks: 
#     - name: Pull redis
#       docker_image:
#         name: redis
#         source: pull

- name: Give execute permission to docker.sock
  hosts: aws
  become: yes
  tasks:
    - name: Give execute permission permisson to docker.sock
      file:
        path: /var/run/docker.sock
        mode: '0777'

- name: Start docker containers
  hosts: aws
  vars_files:
    - project-vars.yaml
  # vars_prompt:
  #   - name: docker_password
  #     prompt: Enter password for docker registry
  tasks:
    - name: Copy docker compose
      copy:
        src: docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Dockerlogin
      docker_login:
        registry_url: https://index.docker.io/v1
        username: hossam1radwan
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose: 
        project_src: /home/ec2-user
        state: present # docker-compose up
    